### ISSUE TITLE
Demo not working on Firefox 51

### ISSUE THREAD

**Issue by Krazitchek** [ErlendEllingsen/pull-to-reload#4]
Error (consol) when pull:

ReferenceError: event is not defined[Learn More]  pull-to-reload.js:100:9
	PullToReload/this.mouseStart https://erlendellingsen.github.io/pull-to-reload/pull-to-reload.js:100:9
	PullToReload/< https://erlendellingsen.github.io/pull-to-reload/pull-to-reload.js:96:9

**Comment by ErlendEllingsen** [comment]
Thanks for the bug-report. Should be resolved now 👍  Care to verify? @Krazitchek

**Comment by Krazitchek** [comment]
Yes, it works now, thanks ! ;-)
